-- AlterTable
ALTER TABLE `User` ADD COLUMN `githubURL` VARCHAR(191) NULL,
    ADD COLUMN `instagramURL` VARCHAR(191) NULL,
    ADD COLUMN `twitterURL` VARCHAR(191) NULL,
    ADD COLUMN `youtubeURL` VARCHAR(191) NULL;
